import '../theme/css/index.css';
import '../theme/css/reset.css';
import '../theme/css/theme.css';
import '../theme/css/globals.css';
import { mulish, tinos } from '#/theme/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${mulish.variable} ${tinos.variable}`}>
      <body>{children}</body>
    </html>
  );
}
